version: '3.7'

services:
  sapanboon:
    image: sapanboon-phx
    restart: always
    ports:
      - 80:${APP_PORT}
    environment:
      - APP_HOSTNAME=${APP_HOSTNAME}
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=ecto://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command: /bin/sh -c "./bin/sapanboon eval Sapanboon.Release.migrate && ./bin/sapanboon start"