use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :sapanboon, SapanboonWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "phx.sapanboon.org", port: 80],
  check_origin: [
    "//beta.api.sapanboon.org",
    "//139.5.145.171:4001"
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  show_sensitive_data_on_connection_error: true

config :sapanboon, SapanboonWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/sapanboon_web/{live,views}/.*(ex)$",
      ~r"lib/sapanboon_web/templates/.*(eex)$"
    ]
  ]

# Config Sending Email with SMTP
config :sapanboon, Sapanboon.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.gmail.com",
  port: 587,
  username: "sapanboon.dev@gmail.com",
  password: "Sapanboon1$",
  tls: :if_available, # can be `:always` or `:never`
  ssl: false, # can be `true`
  retries: 1

config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: "581587157167-s2l0vlfofdj5f0uij76ln11o3toruohh.apps.googleusercontent.com", #made up code
  client_secret: "HlMNukHSTN9-z_O8WeDMUp8J" #made up code

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: "119501292726732",
  client_secret: "8224f14476e6b53e22d586dfce131764"

# Do not print debug messages in production
config :logger, level: :info

config :sapanboon, :api_transaction, "https://beta.api.sapanboon.org"
config :sapanboon, :admin_page, "https://beta.admin.sapanboon.org/sapanboon/?uid="
config :sapanboon, :login_page, "https://phx.sapanboon.org/login"